### PR TITLE
Make the daily mail look damn sexy !

### PR DESCRIPTION
**Pull request by vdaubry**
Include the migration with some metadata about link (image + description)

Re-run the rake db:seed to test

URL to test : http://localhost:5000/rails/mailers/digest_mailer/send_digest

### CODE REVIEW

**Comment by tibo** [comment]
are theses buffer and pocket links working? 
overwise it might worth keeping this as a full feature for an other time? don't you think?

**Comment by vdaubry** [comment]
My bad we should hide them untill it's implemented
Le 28 juin 2015 17:22, "Thibaut LE LEVIER" notifications@github.com a
écrit :

**Comment by vdaubry** [comment]
@tibo : should be good now

**Comment by vdaubry** [comment]
solves #12

**Pull request merged**
