### PR TITLE
add wordcount and estimated reading duration

### PR DESCRIPTION
**Pull request by tibo**

### CODE REVIEW

**Comment by tibo** [comment]
@vdaubry will rebase this one when the others PRs will be merged

**Comment by vdaubry** [comment]
Are you sending all links to pocket ?

We can compute word count without creating a dependendy on an external service : 

Use nokogiri to extract text from html :
`text = Nokogiri::HTML(page_html).text`

Use a text analyzer to count number of words, this one seems robust : [words_counted](https://github.com/abitdodgy/words_counted)
`word_count = WordsCounted.count(text)`

We can merge this in the fetch meta job, since we are already downloading the html to get meta tags, we could just compute the word count at the same time

**Comment by tibo** [comment]
@vdaubry I guess we should just forget this one and keep the feature for later

**Comment by vdaubry** [comment]
It's a cool idea and I think this PR is 70% good, i'll try to have a look at this week

**Comment by vdaubry** [comment]
@tibo : Ready for test.

I didn't include the duration in the mail digest, it's only displayed on the web for now. 
Maybe we should let this run for a day or 2 in prod and, check that it works fine before including it in the mail.

**Pull request merged**
