### PR TITLE
Twitter connect

### PR DESCRIPTION
**Pull request by vdaubry**
Ongoing work for Twitter oauth support

### CODE REVIEW

**Comment by vdaubry** [comment]
@tibo : I created a twitter app that belongs to my twitter account. I don't think you can share permission on twitter apps (?)
Should we create a Twitter account for linkastor ?

**Comment by tibo** [comment]
hum idk, why not having this under a shared account.
let's put the keys in system variable (can we do that with scalingo?)

2015-04-06 23:54 GMT+02:00 vincent daubry notifications@github.com:

**Comment by vdaubry** [comment]
Yep, select [environment ](https://my.scalingo.com/apps/linkastor/variables) in the menu

All keys are already in environment variables :bowtie: 

I'm using foreman also in development, so environment variables are loaded that way.

**Comment by vdaubry** [comment]
@tibo : you can have a look at it, i followed the sign up flow from linkydink :

Twitter connect 
-> Redirects user to a page where you must fill your email address

It works (though the user edit html would need some love...)

**Comment by tibo** [comment]
can't we get the email from the twitter profile?

**Comment by vdaubry** [comment]
No they don't provide the user email address... The recommended approach is to redirect the user to an email form after authentication succeeds : https://twittercommunity.com/t/twitter-oauth-after-connect-get-primary-email-address/1563

I used a real response from Twitter in the [Oauth::Authorization](lib/oauth/authorization.rb) spec , you can look at all informations returned

**Comment by tibo** [comment]
ok. cool!
I guess we will be able to talk about the authentication (maybe provide few other providers?) later

**Pull request merged**
