### PR TITLE
Custom source

### PR DESCRIPTION
**Pull request by vdaubry**

### CODE REVIEW

**Comment by vdaubry** [comment]
This is a first step: we can add "CustomSource" to a user. Right now the only source type is twitter. Everyday it will pull new tweets and include them in the daily mail.

Now that's it's done i realize that Groups should also be source. We have this base class which is a link source, and then we have different class that inherit from source :
Group are a source of links shared by a group of people
Twitter is a source that we will pull for links
RSS feeds are going to be the same
etc

**Comment by vdaubry** [comment]
@tibo ok i'ts done, you can review this PR

**Comment by tibo** [comment]
I've got this error when running the migration
`LINE 1: ... NULL, "type" character varying NOT NULL, "extra" jsonb NOT ...`
@vdaubry any idea?

**Comment by vdaubry** [comment]
Can you post the full error message ?

What's your version on postgres ? The jsonb format is available since 9.4 i
think

I've got this error when running the migration
LINE 1: ... NULL, "type" character varying NOT NULL, "extra" jsonb NOT ...
@vdaubry https://github.com/vdaubry any idea?

**Comment by tibo** [comment]
my bad, I was running postgres 9.2.4

**Comment by tibo** [comment]
the RSS feed adaptor isn't working?

**Comment by vdaubry** [comment]
Not yet, it should be quite easy to implement. I'm working on the rails
generator first, after that it will be very fast to add adaptors
Le 25 juin 2015 18:02, "Thibaut LE LEVIER" notifications@github.com a
écrit :

**Comment by tibo** [comment]
cool.
do you want to have it merged now then? or should we wait to have the whole thing finished?

**Comment by vdaubry** [comment]
Better merge it now, we should already be able to add some twitter feed to the daily mail

**Pull request merged**
