### PR TITLE
display groups and links, add a link

### PR DESCRIPTION
**Pull request by tibo**

### CODE REVIEW

**Comment by tibo** [comment]
@vdaubry take a look at the form itself.
you may have a better idea on how to pass the token (to be able to use it from javascript)

**Comment by vdaubry** [comment]
Well, if the backend generates the form we don't really need to post the link in JS through the API, you could  just do a regular HTML POST. 
If we do a chrome extension, then the API will be usefull.

Let me just play a little bit with this, if it works we can still merge it and simplify it later.

**Comment by tibo** [comment]
The API will still be useful when we will be back on the Chrome Ext (soon enough I guess)
I just figured that using the API was the best way to mutualize the link creation

**Comment by vdaubry** [comment]
Works for me

**Pull request merged**
