### PR TITLE
Groups and invites

### PR DESCRIPTION
**Pull request by vdaubry**
Ongoing work for creating groups and sending email invitations

### CODE REVIEW

**Comment by vdaubry** [comment]
So the sign up workflow will look like this :

Twitter connect 
-> Redirect to user edit (choose an email to receive daily digests)
-> Redirect to group new (create your first group)

When creating the group you give a list of emails for people you want to invite to this group. They will all receive an email with a link to create an account :

Twitter connect 
-> We automatically use the email address from the invite (no need to redirect to user edit)
-> We automatically add them to the group from the invite (no need to redirect to group new)

(and as always :  it's only now that i realize this project is a little bit more complex than i thought initially ;)

**Comment by vdaubry** [comment]
@tibo plop

**Comment by vdaubry** [comment]
@tibo FYI : It's not ready to merge, tell me what you think and i should finish this quite soon.

**Comment by vdaubry** [comment]
@tibo : Ok now it works ! There's quite a lot of corner cases with email invitation, tell me if anything breaks when you test it.

Views are really barebone at the moment, we need to discuss the design

**Comment by vdaubry** [comment]
selfie-0

**Comment by vdaubry** [comment]
selfie-0

**Comment by tibo** [comment]
selfie-0
I'm on it

**Comment by vdaubry** [comment]
I checked it this morning : "It works on my laptop" ©

2015-04-11 14:47 GMT+02:00 Thibaut LE LEVIER notifications@github.com:

> [image: selfie-0]
> https://camo.githubusercontent.com/c75190e1dbfc6a4199b0bcbaf983226f711fdb65/687474703a2f2f692e696d6775722e636f6d2f58586f754e41642e706e67
> I'm on it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Linkastor/Linkastor/pull/3#issuecomment-91837312.

## 

Vincent Daubry
CTO de Youboox
87 rue la Boétie
75008 Paris |+ 33 (0)1 51 50 21 73Website http://www.youboox.fr/ -
Facebook https://www.facebook.com/YoubooxOfficiel - Twitter
https://twitter.com/youboox

Retrouvez nous sur Facebook http://on.fb.me/youboox-FB et Twitter
http://bit.ly/Youboox-Twitter

Téléchargez Youboox sur l'Appstore http://bit.ly/y7hO61

**Pull request merged**
